CREATE TABLE Dimension.Time2
(
	TimeKey INT NOT NULL,
	HourOfDay12 TINYINT NOT NULL,
	HourOfDay24 TINYINT NOT NULL,
	AMPM CHAR(2) NOT NULL,
	MinuteOfHour TINYINT NOT NULL,
	MinuteOfDay SMALLINT NOT NULL,
	SecondOfMinute TINYINT NOT NULL,
	SecondOfHour SMALLINT NOT NULL,
	SecondOfDay INT NOT NULL,
	Time12 CHAR(8) NOT NULL,
	Time12AMPM CHAR(11) NOT NULL,
	Time24 CHAR(8) NOT NULL,
	CONSTRAINT PK_Time2 PRIMARY KEY (TimeKey)
)
