CREATE TABLE Dimension.Time
(
	TimeKey SMALLINT NOT NULL,
	HourOfDay12 TINYINT NOT NULL,
	HourOfDay24 TINYINT NOT NULL,
	AMPM CHAR(2) NOT NULL,
	MinuteOfHour TINYINT NOT NULL,
	MinuteOfDay SMALLINT NOT NULL,
	Time12 CHAR(5) NOT NULL,
	Time12AMPM CHAR(8) NOT NULL,
	Time24 CHAR(5) NOT NULL,
	CONSTRAINT PK_Time PRIMARY KEY (TimeKey)
)
