CREATE TABLE Dimension.DateFY
(
	DateKey                   int              NOT NULL,
	FiscalYearSetKey          varchar(3)       NOT NULL,
	FiscalYearName            char(4)          NOT NULL,
	FiscalYearLongName        varchar(20)      NOT NULL,
	FiscalYearShortName       varchar(10)      NOT NULL,
	FiscalYearAbbreviation    char(2)          NOT NULL,
	FiscalYearBegin           date             NOT NULL,
	FiscalYearEnd             date             NOT NULL,
	FiscalQuarterKey          char(6)          NOT NULL,
	FiscalQuarterName         varchar(20)      NOT NULL,
	FiscalQuarterLongName     varchar(30)      NOT NULL,
	FiscalQuarterAbbreviation char(3)          NOT NULL,
	FiscalQuarterBegin        date             NOT NULL,
	FiscalQuarterEnd          date             NOT NULL,
	FiscalQuarterOfYear       tinyint          NOT NULL,
	FiscalPeriodKey           char(6)          NOT NULL,
	FiscalPeriodName          varchar(20)      NOT NULL,
	FiscalPeriodOfYear        tinyint          NOT NULL,
	FiscalWeekKey             char(7)          NOT NULL,
	FiscalWeekName            varchar(15)      NOT NULL,
	FiscalWeekLongName        varchar(25)      NOT NULL,
	FiscalWeekAbbreviation    varchar(8)       NOT NULL,
	FiscalWeekDescription     varchar(40)      NOT NULL,
	FiscalWeekOfYear          tinyint          NOT NULL,
	FiscalDayOfYear           smallint         NOT NULL,
    CONSTRAINT PK_DateFY PRIMARY KEY (DateKey, FiscalYearSetKey)
)
